name: Deploy Node Application

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t natztheking/nodejs-app .
      - name: Publish Image to docker hub
        run: docker push natztheking/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker push natztheking/nodejs-app:latest
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name nodejs-app-container -e MONGOURI='${{secrets.MONGOURI}}'
